export interface Colors {
  arithmeticOperator: string
  assignmentOperators: string
  blockDelimiters: string
  comments: string
  constants: string
  embeddedCodeDelimiters: string
  enumConstants: string
  enumType: string
  functionNames: string
  glslArithmeticOperator: string
  glslAssignmentOperator: string
  glslBitwiseOperator: string
  glslComparativeOperator: string
  glslConstModifier: string
  glslDefaultText: string
  glslIncrementDecrementOperator: string
  glslNumericConstant: string
  glslPrecisionModifier: string
  glslPreprocessorDirective: string
  glslStorageModifier: string
  glslStorageType: string
  glslSupportFunction: string
  glslSupportVariable: string
  illegalSyntax: string
  illegalTokens: string
  keywords: string
  markupElements: string
  members: string
  methods: string
  modifiers: string
  namespace: string
  numericConstants: string
  parameters: string
  pointerOperators: string
  properties: string
  relationalOperators: string
  storageTypes: string
  strings: string
  structType: string
  typeAnnotation: string
  typeNames: string
  variables: string
}
